# Libs for English
# Translate By Baidu!

libs = {

"100": "the server only receives some requests. If the server does not reject the requests, the client should continue to send the remaining requests.",

"101": "server conversion protocol: the server converts to another protocol according to the request of the client.",

"103": "it is used to suggest recovery requests when recovery of put or post requests fails.",

"200": "request succeeded",

"201": "the request is created and a new resource is created.",

"202": "the request for processing was accepted, but the processing was not completed.",

"203": "the request has been successfully processed, but some response headers may be incorrect because copies of other documents are used.",

"204": "the request has been processed successfully, but no new document has been returned. The browser should continue to display the original document. This status code is useful if the user refreshes the page regularly and the servlet can determine that the user's document is new enough.",

"205": "the request has been processed successfully, but no new document has been returned. However, the browser should reset the content displayed. It is used to force the browser to clear the form input content.",

"206": "the client sends a get request with a range header, and the server completes it.",

"300": "multiple selection. Link list. The user can select a link to reach the destination. Up to five addresses are allowed.",

"301": "the requested page has been transferred to a new URL.",

"302": "the requested page has been temporarily transferred to a new URL.",

"303": "the requested page can be found under another URL.",

"304": "the document is not modified as expected. The client has a buffered document and sends a conditional request (generally, the if modified since header is provided to indicate that the client only wants the document updated than the specified date). The server tells the client that the original buffered document can still be used.",

"305": "the document requested by the client should be extracted through the proxy server specified in the location header.",

"306": "it is no longer used, but the code is still reserved.",

"307": "the requested page has been temporarily moved to a new URL.",

"308": "it is used to suggest recovery requests when recovery of put or post requests fails.",

"400": "the server failed to understand the request because of a syntax error.",

"401": "legitimate request, but access to the requested page is prohibited. Because the requested page requires authentication, the client does not provide it or the authentication fails.",

"402": "this code is not yet available.",

"403": "legitimate request, but access to the requested page is prohibited.",

"404": "the server cannot find the requested page.",

"405": "the method specified in the request is not allowed.",

"406": "the response generated by the server cannot be accepted by the client.",

"407": "the user must first use the proxy server for authentication before the request can be processed.",

"408": "the request exceeds the waiting time of the server.",

"409": "the request could not be completed due to a conflict.",

"410": "the requested page is not available.",

"411": "\" content length \"is not defined. If there is no such content, the server will not accept the request.",

"412": "the preconditions in the request are evaluated as failed by the server.",

"413": "the server will not accept the request because the requested entity is too large.",

"414": "the server will not accept the request because the URL is too long. This happens when a post request is converted to a get request with very long query information.",

"415": "the server will not accept the request because the media type is not supported.",

"416": "the client requests part of the document, but the server cannot provide the requested part.",

"417": "the server cannot satisfy the request header specified by the client in the request.",

"500": "the request was not completed. The server encountered unpredictable conditions.",

"501": "the request is not completed. The server does not support the requested function, or the server cannot complete the request.",

"502": "the request is not completed. When the server acts as a gateway or proxy, it receives an invalid response from the upstream server.",

"503": "the server is currently unavailable (overloaded or down).",

"504": "gateway timeout. When the server acts as a gateway or proxy, it fails to receive a timely response from the upstream server.",

"505": "the server does not support the HTTP protocol version specified in the request.",

"511": "users need to provide authentication to obtain network access."
